AllCops:
  Exclude:
    - vendor/**/*
    - example/**/*

inherit_from: .rubocop_todo.yml

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Metrics/LineLength:
  Exclude:
    - spec/**/*

Metrics/MethodLength:
  Exclude:
    - spec/**/*

Style/IndentHash:
  EnforcedStyle: consistent
