inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - vendor/**/*
    - example/**/*
  TargetRubyVersion: 2.4

Layout/EmptyLinesAroundArguments:
  Enabled: false

Layout/IndentFirstHashElement:
  EnforcedStyle: consistent

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Metrics/ClassLength:
  Max: 300

Metrics/LineLength:
  Max: 120
  Exclude:
    - spec/**/*

Metrics/MethodLength:
  Exclude:
    - spec/**/*

Naming:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false
