inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - vendor/**/*
    - example/**/*
  TargetRubyVersion: 2.7

#  Layout stuff
#
Layout/EmptyLinesAroundArguments:
  Enabled: false

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/LineLength:
  Max: 120
  Exclude:
    - spec/**/*

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

# Lint stuff
#
Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

# Metrics stuff
#
Metrics/BlockLength:
  Exclude:
    - spec/**/*

Metrics/ClassLength:
  Max: 300

Metrics/MethodLength:
  Exclude:
    - spec/**/*

# Naming stuff
#
Naming:
  Enabled: false

# Style stuff
#
Style/ExponentialNotation:
  Enabled: true

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/RegexpLiteral:
  Enabled: false

Metrics/CyclomaticComplexity:
  Max: 14
