AllCops:
  Exclude:
    - vendor/**/*
    - example/**/*
  TargetRubyVersion: 2.4

inherit_from: .rubocop_todo.yml

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Metrics/LineLength:
  Exclude:
    - spec/**/*

Metrics/MethodLength:
  Exclude:
    - spec/**/*

Style/IndentHash:
  EnforcedStyle: consistent

Style/FileName:
  Enabled: false
