name: Rubocop

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  rubocop:
    name: Rubocop
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '3.0'
      - run: gem install rubocop --no-doc
      - run: rubocop --format progress --format json --out rubocop.json
        id: rubocop
      - uses: duderman/rubocop-annotate-action@v0.1.0
        with:
          path: rubocop.json
        if: ${{ failure() }}
